spring.datasource.url=jdbc:postgresql://localhost:5432/palm_lockers
spring.datasource.username=postgres
spring.datasource.password=tienson

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

esp32.ip=http://172.20.10.6